config/routes.rb
Rails.application.routes.draw do
  scope '/dashboard' do
      resources :parts, :vendors, :policies, :roles, :part_orders, :work_orders, :work_order_requests
      get 'part/search', to: 'parts#search'
      get 'vendor/search', to: 'vendors#search'
      get 'role/search', to: 'roles#search'
      get 'policy/search', to: 'policies#search'
      get 'part_order/search', to: 'part_orders#search'
      get 'part_order/search_vendor', to: 'part_orders#search_vendor'
      get 'part_order/search_name', to: 'part_orders#search_name'
      get 'work_order/calendar', to: 'work_orders#calendar'
      get 'work_order/events', to: 'work_orders#events'
      post 'work_order_requests/:id/confirm', to: 'work_order_requests#confirm', as: :work_order_request_confirm
      post 'work_order_requests/:id/deny', to: 'work_order_requests#deny', as: :work_order_request_deny
      get 'part_order/:id/receipt', to: "part_orders#receipt", as: :part_order_receipt
      get 'part_order_receipts', to: "part_orders#receipts", as: :part_order_receipts
      put 'part_items/:id', to: "part_items#update", as: :part_item_update
  end
  get 'dashboard_unauth/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboard#index"

  get 'dashboard/users', to: 'users#index'
  put 'dashboard/users/:id', to: 'users#update_role', as: :user_update_roles

  get 'dashboard_unauth/orders', to: 'dashboard_unauth#orders'
  get 'dashboard_unauth/products', to: 'dashboard_unauth#products'
  get 'dashboard_unauth/customers', to: 'dashboard_unauth#customers'
  get 'dashboard_unauth/users', to: 'dashboard_unauth#users'
  get 'dashboard_unauth/departments', to: 'dashboard_unauth#departments'



end

app/models/part.rb
class Part < ApplicationRecord
	  has_and_belongs_to_many :vendors
	  has_one_attached :main_image
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_active_storage_host
  before_action :force_json, only: :search
  layout 'dashboard'

  def set_active_storage_host
    ActiveStorage::Current.host = 'http://localhost:3000' if ActiveStorage::Current.host.blank?
    true
  end

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  def search
    
    if params.has_key?(:q)
      q = params[:q].downcase
      @parts = Part.where("barcode LIKE ?", "%#{q}%").limit(5)
    elsif params.has_key?(:mfr_number)
      mfr = params[:mfr_number].downcase
      @parts = Part.where("mfr_number LIKE ?", "%#{mfr}%").limit(5)
    elsif params.has_key?(:machine)
      machine = params[:machine].downcase
      @parts = Part.where("machine LIKE ?", "%#{machine}%").limit(5)
    elsif params.has_key?(:location)
      location = params[:location].downcase
      @parts = Part.where("location LIKE ?", "%#{location}%").limit(5)
    end

  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    def force_json
      request.format = :json
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:name, :description, :location, :quantity, :mfr_number, :barcode, :machine, :main_image, vendor_ids: [])
    end
end

app/helpers/parts_helper.rb
module PartsHelper


	def options_for_vendor
	  	Vendor.all.map { |e| [e.name, e.id]  }
	end

end

app/views/parts/_form.html.erb
<div class="card-container">
  
  <div class="card">
    <div class="card-header">
      Parts
    </div>
    <div class="card-body">

      <div class="row">
        <div class="col-md-6">
          <%= form_with(model: part) do |form| %>
            <% if part.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

                <ul>
                  <% part.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <%= form.label :main_image %>
              <%= form.file_field :main_image, class: "form-control-file" %>
            </div>

            <div class="form-group">
              <%= form.label :name %>
              <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :description %>
              <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :location %>
              <%= form.text_field :location, class: "form-control", data: {behavior: "autocomplete-location"} %>
            </div>

            <div class="form-group">
              <%= form.label :quantity %>
              <%= form.number_field :quantity, class: "form-control" %>
            </div>

           
            <div class="form-group">
              <%= form.label :mfr_number %>
              <%= form.text_field :mfr_number, class: "form-control", data: {behavior: "autocomplete"} %>
            </div>

            <div class="form-group">
              <%= form.label :barcode %>
              <%= form.text_field :barcode, class: "form-control", data: {behavior: "autocomplete-barcode"}  %>
            </div>

            <div class="form-group">
              <%= form.label :machine %>
              <%= form.text_field :machine, class: "form-control", data: {behavior: "autocomplete-machine"} %>
            </div>

            <div class="form-group">
              <%= form.label :vendors %>
              <%= form.select :vendor_ids, options_for_vendor, {}, {:multiple => true, class: "form-control" } %>
            </div>

            <div class="actions">
              <%= form.submit "Submit", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>
<p id="notice"><%= notice %></p>
<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Parts
  </div>
  <div class="card-body">
    <p class="card-text">Part Search (Enter Parameters)</p>
     <div class="form-group row">
    <label for="championPart" class="col-sm-2 col-form-label">Champion Part #</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="championPart">
    </div>
  </div>
  <div class="form-group row">
    <label for="championPart" class="col-sm-2 col-form-label">OEM Part #</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="championPart">
    </div>
  </div>
  <div class="form-group row">
    <label for="championPart" class="col-sm-2 col-form-label">MFG Part #</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="championPart">
    </div>
  </div>
  <div class="table-responsive">
        <table class="table table-striped table-sm" id="table-work-orders">
          <thead>
            <tr>
              <th>Image</th>
              <th>ID</th>
              <th>Name</th>
              <th>Description</th>
              <th>Location</th>
              <th>Quantity</th>
              <th>Mfr number</th>
              <th>Barcode</th>
              <th>Machine</th>
              <th>Vendors</th>
              <th colspan="3"></th>
              <th style="display: none"></th> 
            </tr>
          </thead>

          <tbody>
            <% @parts.each do |part| %>
              <tr>
                <td><% unless part.main_image.url.nil? %><%= image_tag part.main_image, style: "width: 50px;" %><% end %></td>
                <td><%= part.id %></td>
                <td><%= part.name %></td>
                <td><%= part.description %></td>
                <td><%= part.location %></td>
                <td><%= part.quantity %></td>
                <td><%= part.mfr_number %></td>
                <td><%= part.barcode %></td>
                <td><%= part.machine %></td>
                <td><%= part.vendors.map(&:name) %>
                <td><%= link_to 'Show', part %></td>
                <td><%= link_to 'Edit', edit_part_path(part) %></td>
                <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td style="display: none"></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

<br>
    <%= link_to 'New Part', new_part_path, class: "btn btn-primary white", style: "float: right;" %>

  </div>
</div>

</div>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @part.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @part.location %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @part.quantity %>
</p>

<p>
  <strong>Mfr number:</strong>
  <%= @part.mfr_number %>
</p>

<p>
  <strong>Barcode:</strong>
  <%= @part.barcode %>
</p>

<p>
  <strong>Machine:</strong>
  <%= @part.machine %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>