config/routes.rb
Rails.application.routes.draw do
  scope '/dashboard' do
      resources :parts, :vendors, :policies, :roles, :part_orders, :work_orders, :work_order_requests
      get 'part/search', to: 'parts#search'
      get 'vendor/search', to: 'vendors#search'
      get 'role/search', to: 'roles#search'
      get 'policy/search', to: 'policies#search'
      get 'part_order/search', to: 'part_orders#search'
      get 'part_order/search_vendor', to: 'part_orders#search_vendor'
      get 'part_order/search_name', to: 'part_orders#search_name'
      get 'work_order/calendar', to: 'work_orders#calendar'
      get 'work_order/events', to: 'work_orders#events'
      post 'work_order_requests/:id/confirm', to: 'work_order_requests#confirm', as: :work_order_request_confirm
      post 'work_order_requests/:id/deny', to: 'work_order_requests#deny', as: :work_order_request_deny
      get 'part_order/:id/receipt', to: "part_orders#receipt", as: :part_order_receipt
      get 'part_order_receipts', to: "part_orders#receipts", as: :part_order_receipts
      put 'part_items/:id', to: "part_items#update", as: :part_item_update
  end
  get 'dashboard_unauth/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboard#index"

  get 'dashboard/users', to: 'users#index'
  put 'dashboard/users/:id', to: 'users#update_role', as: :user_update_roles

  get 'dashboard_unauth/orders', to: 'dashboard_unauth#orders'
  get 'dashboard_unauth/products', to: 'dashboard_unauth#products'
  get 'dashboard_unauth/customers', to: 'dashboard_unauth#customers'
  get 'dashboard_unauth/users', to: 'dashboard_unauth#users'
  get 'dashboard_unauth/departments', to: 'dashboard_unauth#departments'



end

app/models/part_order.rb
class PartOrder < ApplicationRecord
	has_many :part_items
	accepts_nested_attributes_for :part_items, reject_if: :all_blank, allow_destroy: true
	enum status: [:open, :closed]
	scope :open, -> { where(status: "open") }
	scope :closed, -> { where(status: "closed") }
end

app/controllers/part_orders_controller.rb
class PartOrdersController < ApplicationController
  before_action :set_part_order, only: %i[ show edit update destroy ]
  layout 'dashboard'

  # GET /part_orders or /part_orders.json
  def index
    @part_orders = PartOrder.open
    @closed_part_orders = PartOrder.closed
    @all_part_orders = PartOrder.all
  end

  def search
    q = params[:q].downcase
    @parts = Part.where("mfr_number LIKE ?", "%#{q}%").limit(5)
  end

  def search_name
    q = params[:q].downcase
    @parts = Part.where("name LIKE ?", "%#{q}%").limit(5)
  end

  def search_vendor
    q = params[:q].downcase
    @vendors = Vendor.where("code LIKE ?", "%#{q}%").limit(5)
  end

  # GET /part_orders/1 or /part_orders/1.json
  def show

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", :template => 'part_orders/pdf.html.erb'   # Excluding ".pdf" extension.
      end
    end
  end

  # GET /part_orders/new
  def new
    @part_order = PartOrder.new
    @part_order.part_items.build
  end

  # GET /part_orders/1/edit
  def edit
  end

  # POST /part_orders or /part_orders.json
  def create
    @part_order = PartOrder.new(part_order_params)

    respond_to do |format|
      if @part_order.save
        format.html { redirect_to @part_order, notice: "Part order was successfully created." }
        format.json { render :show, status: :created, location: @part_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /part_orders/1 or /part_orders/1.json
  def update
    respond_to do |format|
      if @part_order.update(part_order_params)
        format.html { redirect_to part_order_receipt_path(@part_order), notice: "Part order was successfully updated." }
        format.json { render :show, status: :ok, location: @part_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /part_orders/1 or /part_orders/1.json
  def destroy
    @part_order.destroy
    respond_to do |format|
      format.html { redirect_to part_orders_url, notice: "Part order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # PO Receipt
  def receipt
    @part_order = PartOrder.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", :template => 'part_orders/receipt.html.erb'   # Excluding ".pdf" extension.
      end
    end
  end

  def receipts
    @part_orders = PartOrder.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part_order
      @part_order = PartOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_order_params
      params.require(:part_order).permit(:part_name, :part_description, :status, :delivery_date, :vendor_id, :po_number, :vendor, :vendor_contact, :vendor_address, :quantity, :total, part_items_attributes: [:id, :description, :name, :quantity, :received, :rate, :_destroy])
    end
end

app/helpers/part_orders_helper.rb
module PartOrdersHelper
end

app/views/part_orders/_form.html.erb
<style>
    .card-container {
        margin-top: 20px;
    }

    .card-header {

        background-color: blue;
        color: white;
    }
</style>
<div class="card-container">

  <div class="card">
    <div class="card-header">
      Parts
    </div>
    <div class="card-body">
      <% if part_order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(part_order.errors.count, "error") %> prohibited this part_order from being saved:</h2>

          <ul>
            <% part_order.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with(model: part_order) do |form| %>
       <h5>Vendor Information</h5>
        <div class="form-group row">

          <label for="SelectVendor" class="col-sm-2 col-form-label">Select Vendor</label>
          <div class="col-sm-4">
            <%= form.text_field :vendor_id,  class: "form-control", data: {behavior: "autocomplete-order-vendors"}  %>
          </div>
        </div>
        <div class="form-group row">
          <label for="VendorName" class="col-sm-2 col-form-label">Vendor Name</label>
          <div class="col-sm-4">
            <%= form.text_field :vendor, class: "form-control"  %>
          </div>
        </div>
        <div class="form-group row">
          <label for="VendorPhoneNumber" class="col-sm-2 col-form-label">Vendor Phone Number</label>
          <div class="col-sm-4">
            <%= form.text_field :vendor_contact, class: "form-control" %>
          </div>
        </div>
        <div class="form-group row">
          <label for="VendorEmail" class="col-sm-2 col-form-label">Vendor Email</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="VendorEmail">
          </div>
        </div>
        <div class="form-group row">
          <label for="VendorAddress" class="col-sm-2 col-form-label">Vendor Address</label>
          <div class="col-sm-4">
            <%= form.text_field :vendor_address, class: "form-control" %>
          </div>
        </div>
    
          
        

        <br>

        <%= react_component("PartItem", { parts: part_order.part_items }) %>
        <div class="form-group row">
          <label for="Delivery" class="col-sm-2 col-form-label">Delivery Date</label>
          <div class="col-sm-2">
            <%= form.text_field :delivery_date, class: "form-control flatpickr" %>
          </div>
          <label for="poNumber" class="col-sm-2 col-form-label">PO Number</label>
          <div class="col-sm-2">
            <%= form.text_field :po_number,  class: "form-control"  %>
          </div>
        </div>
        <br>

       

        
           
 
          


        <br>
        <%= form.submit "Save and Close", class: "btn btn-primary" %>

        <a href="#" class="btn btn-primary" style="float: right;">Cancel</a>
        </div>
        </div>
      <% end %>

      </div>


</div>
</div>

app/views/part_orders/_part_fields.html.erb
<tr>
	<td>
		<div class="field">
			<%= f.text_field :name, class: "form-control" %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :description, class: "form-control" %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :quantity, class: "form-control" %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :rate, class: "form-control" %>
		</div>
	</td>
	<td>
		<%= link_to_remove_association "remove part", f %>
	</td>
</tr>

app/views/part_orders/edit.html.erb
<h1>Editing Part Order</h1>

<%= render 'form', part_order: @part_order %>

<%= link_to 'Show', @part_order %> |
<%= link_to 'Back', part_orders_path %>

app/views/part_orders/index.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Part Orders
  </div>
  <div class="card-body">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="open-tab" data-toggle="tab" href="#open" role="tab" aria-controls="open" aria-selected="true">Open</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="closed-tab" data-toggle="tab" href="#closed" role="tab" aria-controls="closed" aria-selected="false">Closed</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="receipt-tab" data-toggle="tab" href="#receipt" role="tab" aria-controls="receipt" aria-selected="false">Receipt</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="open" role="tabpanel" aria-labelledby="open-tab">
        <div class="table-responsive">
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th>PO Number</th>
                    <th>Delivery Date</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @part_orders.each do |part| %>
                    <tr>
                      <td><%= part.id %></td>
                      <td><%= part.delivery_date %></td>
                      <td><%= link_to 'Show', part %></td>
                      <td><%= link_to 'Edit', edit_part_order_path(part) %></td>
                      <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
        </div>
    </div>
    <div class="tab-pane fade" id="closed" role="tabpanel" aria-labelledby="closed-tab">
      <div class="table-responsive">
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th>PO Number</th>
                    <th>Delivery Date</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @closed_part_orders.each do |part| %>
                    <tr>
                      <td><%= part.id %></td>
                      <td><%= part.delivery_date %></td>
                      <td><%= link_to 'Show', part %></td>
                      <td><%= link_to 'Edit', edit_part_order_path(part) %></td>
                      <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
        </div>
    </div>
    <div class="tab-pane fade" id="receipt" role="tabpanel" aria-labelledby="receipt-tab">
      <div class="table-responsive">
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th>PO Number</th>
                    <th>Delivery Date</th>
                    <th>Status</th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>
                  <% @all_part_orders.each do |part| %>
                    <tr>
                      <td><%= part.id %></td>
                      <td><%= part.delivery_date %></td>
                      <td><%= part.status %></td>
                      <td><%= link_to 'Show', part_order_receipt_path(part) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
        </div>
    </div>
  </div>


<br>
    <%= link_to 'New Part Order', new_part_order_path, class: "btn btn-primary white", style: "float: right;" %>

  </div>
</div>

</div>

app/views/part_orders/new.html.erb
<%= render 'form', part_order: @part_order %>

<%= link_to 'Back', part_orders_path %>

app/views/part_orders/pdf.html.erb
<div class="row" style="background-color: blue; color: white;">
	<div class="col-md-12">
		Part Order
	</div>
</div>
<div class="row">
	<div class="col-12">
		Vendor Name: <%= @part_order.vendor %>
	</div>
</div>
<div class="row">
	<div class="col-12">
		Vendor Phone Number: <%= @part_order.vendor_contact %>
	</div>
</div>
<div class="row">
	<div class="col-12">
		Vendor Address: <%= @part_order.vendor_address %>
	</div>
</div>
<div class="row">
	<div class="col-12">
		Delivery Date: <%= @part_order.delivery_date %>
	</div>
</div>
<hr>
  <div class="table-responsive">
  		
        <table class="table table-striped" id="table-work-orders"> 
          <thead>
            <tr>
              <th style="width:200px; text-align: left;">Part Name</th>
              <th style="width:200px; text-align: left;">Part Description</th>
              <th style="width:200px; text-align: left;">Quantity</th>
              <th style="width:200px; text-align: left;">Rate</th>
            </tr>
          </thead>

          <tbody>
          	  <% @part_order.part_items.each do |t| %>
              <tr>
                <td><%= t.name %></td>
                <td><%= t.description %></td>
                <td><%= t.quantity %></td>
                <td><%= t.rate %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>

app/views/part_orders/receipt.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-sm-12">
		<%= link_to 'Export to PDF', part_order_path(@part_order, format: "pdf"), class: "btn btn-primary white", style: "float: right;" %>
	</div>
</div>

<div class="card-container">
  <%= form_with(url: part_order_path(@part_order), method: "put")  do |f| %> 
  <div class="card">
  <div class="card-header">
    Part Oder for PO - <%= @part_order.id %>
  </div>
  <div class="card-body">
  	<div class="row">
		<div class="col-12">
			Vendor Name: <%= @part_order.vendor %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			Vendor Phone Number: <%= @part_order.vendor_contact %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			Vendor Address: <%= @part_order.vendor_address %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			Delivery Date: <%= @part_order.delivery_date %>
		</div>
	</div>
	<hr>
  
  <div class="table-responsive">
  		
        <table class="table table-striped table-sm" id="table-work-orders"> 
          <thead>
            <tr>
              <th>Part Name</th>
              <th>Part Description</th>
              <th>Quantity</th>
              <th>Rate</th>
              <th>Received</th>
            </tr>
          </thead>

          <tbody>
            
          	  <% @part_order.part_items.each_with_index do |t, i| %>
              <tr>
                <td><%= t.name %></td>
                <td><%= t.description %></td>
                <td><%= t.quantity %></td>
                <td><%= t.rate %></td>
                <td>
                  <%= f.hidden_field "part_order[part_items_attributes][" + i.to_s + "][id]", value: t.id %>
                    <%= f.number_field "part_order[part_items_attributes][" + i.to_s + "][received]", value: t.received %>
                </td>
              </tr>
              <% end %>
              <tr>
                <td></td>
                <td></td>
                <td style="font-weight: bold">TOTAL</td>
                <td><%= @part_order.total %></td>
                <td></td>
              </tr>
          </tbody>
        </table>
      </div>
      

<br>

	
	<%= link_to 'Back', part_orders_path, class: "btn btn-primary white" %>
  <%= f.submit "Update", class: "btn btn-primary white", style: "float: right;" %>

  </div>
  <% end %>
</div>

</div>

app/views/part_orders/receipts.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>

<p id="notice"><%= notice %></p>

<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Part Order Receipts
  </div>
  <div class="card-body">
   <div class="table-responsive">
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th>PO Number</th>
                    <th>Delivery Date</th>
                    <th>Status</th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>
                  <% @part_orders.each do |part| %>
                    <tr>
                      <td><%= part.id %></td>
                      <td><%= part.delivery_date %></td>
                      <td><%= part.status %></td>
                      <td><%= link_to 'Show', part_order_receipt_path(part) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
        </div>


  </div>
</div>

</div>

app/views/part_orders/show.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>

<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-sm-12">
    <button class="btn btn-primary white" style="float: right; margin-left: 10px;" onclick="printDiv('part-order-card')">Print</button>
		<%= link_to 'Export to PDF', part_order_path(@part_order, format: "pdf"), class: "btn btn-primary white", style: "float: right;" %>
	</div>
</div>

<div class="card-container" id="part-order-card">
  
  <div class="card">
  <div class="card-header">
    Part Oder for PO - <%= @part_order.id %>
  </div>
  <div class="card-body">
  	<div class="row">
		<div class="col-12">
			Vendor Name: <%= @part_order.vendor %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			Vendor Phone Number: <%= @part_order.vendor_contact %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			Vendor Address: <%= @part_order.vendor_address %>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			Delivery Date: <%= @part_order.delivery_date %>
		</div>
	</div>
	<hr>
  <div class="table-responsive">
  		
        <table class="table table-striped table-sm" id="table-work-orders"> 
          <thead>
            <tr>
              <th>Part Name</th>
              <th>Part Description</th>
              <th>Quantity</th>
              <th>Rate</th>
            </tr>
          </thead>

          <tbody>
          	  <% @part_order.part_items.each do |t| %>
              <tr>
                <td><%= t.name %></td>
                <td><%= t.description %></td>
                <td><%= t.quantity %></td>
                <td><%= t.rate %></td>
              </tr>
              <% end %>
              <tr>
                <td></td>
                <td></td>
                <td style="font-weight: bold">TOTAL</td>
                <td><%= @part_order.total %></td>
              </tr>
          </tbody>
        </table>
      </div>

<br>
	
	<%= link_to 'Back', part_orders_path, class: "btn btn-primary white" %>


  </div>
</div>

</div>
<script>
  function printDiv(divName) {

     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;
     window.print();

     document.body.innerHTML = originalContents;
}
  </script>