config/routes.rb
Rails.application.routes.draw do
  scope '/dashboard' do
      resources :parts, :vendors, :policies, :roles, :part_orders, :work_orders, :work_order_requests
      get 'part/search', to: 'parts#search'
      get 'vendor/search', to: 'vendors#search'
      get 'role/search', to: 'roles#search'
      get 'policy/search', to: 'policies#search'
      get 'part_order/search', to: 'part_orders#search'
      get 'part_order/search_vendor', to: 'part_orders#search_vendor'
      get 'part_order/search_name', to: 'part_orders#search_name'
      get 'work_order/calendar', to: 'work_orders#calendar'
      get 'work_order/events', to: 'work_orders#events'
      post 'work_order_requests/:id/confirm', to: 'work_order_requests#confirm', as: :work_order_request_confirm
      post 'work_order_requests/:id/deny', to: 'work_order_requests#deny', as: :work_order_request_deny
      get 'part_order/:id/receipt', to: "part_orders#receipt", as: :part_order_receipt
      get 'part_order_receipts', to: "part_orders#receipts", as: :part_order_receipts
      put 'part_items/:id', to: "part_items#update", as: :part_item_update
  end
  get 'dashboard_unauth/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboard#index"

  get 'dashboard/users', to: 'users#index'
  put 'dashboard/users/:id', to: 'users#update_role', as: :user_update_roles

  get 'dashboard_unauth/orders', to: 'dashboard_unauth#orders'
  get 'dashboard_unauth/products', to: 'dashboard_unauth#products'
  get 'dashboard_unauth/customers', to: 'dashboard_unauth#customers'
  get 'dashboard_unauth/users', to: 'dashboard_unauth#users'
  get 'dashboard_unauth/departments', to: 'dashboard_unauth#departments'



end

app/models/vendor.rb
class Vendor < ApplicationRecord
	 has_and_belongs_to_many :parts

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :force_json, only: :search
  layout 'dashboard'

  # GET /vendors or /vendors.json
  def index
    @vendors = Vendor.all
  end

  def search
      q = params[:q].downcase
      @vendors = Vendor.where("name LIKE ?", "%#{q}%").limit(5)
  end


  # GET /vendors/1 or /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors or /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: "Vendor was successfully created." }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: "Vendor was successfully updated." }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: "Vendor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def force_json
      request.format = :json
    end


    # Only allow a list of trusted parameters through.
    def vendor_params
      params.require(:vendor).permit(:name, :contact_person, :address, :code, :phone_number, :email_address)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: vendor) do |form| %>
      <% if vendor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

          <ul>
            <% vendor.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :vendor_code %>
        <%= form.text_field :code, class: "form-control", data: {behavior: "autocomplete-vendors"} %>
      </div>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :contact_person %>
        <%= form.text_field :contact_person, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :email_address %>
        <%= form.text_field :email_address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>
<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Vendors Search
  </div>
  <div class="card-body">
    <p class="card-text">Vendor Search (Enter Parameters)</p>
     <div class="form-group row">
    <label for="vendorName" class="col-sm-2 col-form-label">Vendor Name</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="vendorName">
    </div>
  </div>
  
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Vendor Code</th>
      <th>Name</th>
      <th>Contact Person</th>
      <th>Phone Number</th>
      <th>Email Address</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.code %></td>
        <td><%= vendor.name %></td>
        <td><%= vendor.contact_person %></td>
        <td><%= vendor.phone_number %></td>
        <td><%= vendor.email_address %></td>
        <td><%= vendor.address %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  
<br>
    <%= link_to 'New Vendor', new_vendor_path, class: "btn btn-primary", style: "float: right; color: white;" %>
  </div>
</div>

</div>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>