config/routes.rb
Rails.application.routes.draw do
  scope '/dashboard' do
      resources :parts, :vendors, :policies, :roles, :part_orders, :work_orders, :work_order_requests
      get 'part/search', to: 'parts#search'
      get 'vendor/search', to: 'vendors#search'
      get 'role/search', to: 'roles#search'
      get 'policy/search', to: 'policies#search'
      get 'part_order/search', to: 'part_orders#search'
      get 'part_order/search_vendor', to: 'part_orders#search_vendor'
      get 'part_order/search_name', to: 'part_orders#search_name'
      get 'work_order/calendar', to: 'work_orders#calendar'
      get 'work_order/events', to: 'work_orders#events'
      post 'work_order_requests/:id/confirm', to: 'work_order_requests#confirm', as: :work_order_request_confirm
      post 'work_order_requests/:id/deny', to: 'work_order_requests#deny', as: :work_order_request_deny
      get 'part_order/:id/receipt', to: "part_orders#receipt", as: :part_order_receipt
      get 'part_order_receipts', to: "part_orders#receipts", as: :part_order_receipts
      put 'part_items/:id', to: "part_items#update", as: :part_item_update
  end
  get 'dashboard_unauth/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboard#index"

  get 'dashboard/users', to: 'users#index'
  put 'dashboard/users/:id', to: 'users#update_role', as: :user_update_roles

  get 'dashboard_unauth/orders', to: 'dashboard_unauth#orders'
  get 'dashboard_unauth/products', to: 'dashboard_unauth#products'
  get 'dashboard_unauth/customers', to: 'dashboard_unauth#customers'
  get 'dashboard_unauth/users', to: 'dashboard_unauth#users'
  get 'dashboard_unauth/departments', to: 'dashboard_unauth#departments'



end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
	enum status: [:pending, :completed]
	scope :completed, -> { where(status: "completed") }
	scope :pending, -> { where(status: "pending") }
	validates :location, :issue, :line, :machine, :work_order_type, :request_date_time, :level_of_issue, :requested_by, :email, :description_of_issue, :planned_date_and_time, :complete_date_and_time, presence: true
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[ show edit update destroy ]
  layout 'dashboard'

  # GET /work_orders or /work_orders.json
  def index
    @work_orders = WorkOrder.pending
    @completed_work_orders = WorkOrder.completed
    @work_order_requests = WorkOrderRequest.pending

  end

  # GET /work_orders/1 or /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders or /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, notice: "Work order was successfully created." }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1 or /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to @work_order, notice: "Work order was successfully updated." }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1 or /work_orders/1.json
  def destroy
    @work_order.destroy
    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: "Work order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def calendar
  end

  def events
    @events = WorkOrder.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_order_params
      params.require(:work_order).permit(:location, :status, :issue, :line, :recurring, :recurring_frequency, :machine, :work_order_type, :request_date_time, :level_of_issue, :requested_by, :email, :description_of_issue, :planned_date_and_time, :complete_date_and_time)
    end
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/_form.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }

  .toggle {
    border: 1px solid lightgrey;
  }
</style>


<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Work Order
  </div>
  <div class="card-body">
<%= form_with(model: work_order) do |form| %>
  <% if work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
        <% work_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :issue %>
    <%= form.text_field :issue, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :line %>
    <%= form.text_field :line, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :machine %>
    <%= form.text_field :machine, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :work_order_type %>
    <%= form.text_field :work_order_type, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :request_date_time %>
    <%= form.text_field :request_date_time, class: "form-control flatpickr", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :level_of_issue %>
    <%= form.text_field :level_of_issue, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :requested_by %>
    <%= form.text_field :requested_by, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description_of_issue %>
    <%= form.text_field :description_of_issue, class: "form-control", required: true %>
  </div>
  <div class="form-group">
     <%= form.label :recurring_option, style: "display: block;" %>
     <%= form.select :recurring_frequency, [['None', "none"], ['Weekly', "weekly"], ['Biweekly', "biweekly"], ['Monthly', "monthly"] ], {}, class: "form-control" %> 

  </div>
  <div class="form-group">
    <%= form.label :planned_date_and_time %>
    <%= form.text_field :planned_date_and_time, class: "form-control flatpickr", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :complete_date_and_time %>
    <%= form.text_field :complete_date_and_time, class: "form-control flatpickr", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, [['Pending', "pending"], ['Completed', "completed"]],{} ,class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/work_orders/calendar.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>
<div class="card-container">
	 <div class="card">
		  <div class="card-header">
		    Work Orders Schedule
		  </div>
		  <div class="card-body">
			<div id="calendar"></div>
		  </div>
		</div>
</div>

app/views/work_orders/edit.html.erb
<h1>Editing Work Order</h1>

<%= render 'form', work_order: @work_order %>

<%= link_to 'Show', @work_order %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>

<p id="notice"><%= notice %></p>

<%= link_to 'Calendar View', work_order_calendar_path , class: "btn btn-outline-primary", style: "float: right;" %>

<br>

<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Work Orders
  </div>
  <div class="card-body">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="true">Pending</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="completed-tab" data-toggle="tab" href="#completed" role="tab" aria-controls="completed" aria-selected="false">Completed</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="pending" role="tabpanel" aria-labelledby="pending-tab">
    <div class="table-responsive">
        <table class="table table-striped table-sm" id="table-work-orders">
          <thead>
            <tr>
              <th>Location</th>
              <th>Issue</th>
              <th>Line</th>
              <th>Machine</th>
              <th>Type</th>
              <th>Request date time</th>
              <th>Level of issue</th>
              <th>Requested by</th>
              <th>Email</th>
              <th>Description of issue</th>
              <th>Planned date and time</th>
              <th>Complete date and time</th>
              <th colspan="3"></th>
              <th style="display: none"></th> 
            </tr>
          </thead>

          <tbody>
            <% @work_orders.each do |work_order| %>
              <tr>
                <td><%= work_order.location %></td>
                <td><%= work_order.issue %></td>
                <td><%= work_order.line %></td>
                <td><%= work_order.machine %></td>
                <td><%= work_order.work_order_type %></td>
                <td><%= work_order.request_date_time %></td>
                <td><%= work_order.level_of_issue %></td>
                <td><%= work_order.requested_by %></td>
                <td><%= work_order.email %></td>
                <td><%= work_order.description_of_issue %></td>
                <td><%= work_order.planned_date_and_time %></td>
                <td><%= work_order.complete_date_and_time %></td>
                <td><%= link_to 'Show', work_order %></td>
                <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
                <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td style="display: none"></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>

  </div>
  <div class="tab-pane fade" id="completed" role="tabpanel" aria-labelledby="completed-tab">
    <div class="table-responsive">
        <table class="table table-striped table-sm" id="completed-table-work-orders">
          <thead>
            <tr>
              <th>Location</th>
              <th>Issue</th>
              <th>Line</th>
              <th>Machine</th>
              <th>Type</th>
              <th>Request date time</th>
              <th>Level of issue</th>
              <th>Requested by</th>
              <th>Email</th>
              <th>Description of issue</th>
              <th>Planned date and time</th>
              <th>Complete date and time</th>
              <th colspan="3"></th>
              <th style="display: none"></th> 
            </tr>
          </thead>

          <tbody>
            <% @completed_work_orders.each do |work_order| %>
              <tr>
                <td><%= work_order.location %></td>
                <td><%= work_order.issue %></td>
                <td><%= work_order.line %></td>
                <td><%= work_order.machine %></td>
                <td><%= work_order.work_order_type %></td>
                <td><%= work_order.request_date_time %></td>
                <td><%= work_order.level_of_issue %></td>
                <td><%= work_order.requested_by %></td>
                <td><%= work_order.email %></td>
                <td><%= work_order.description_of_issue %></td>
                <td><%= work_order.planned_date_and_time %></td>
                <td><%= work_order.complete_date_and_time %></td>
                <td><%= link_to 'Show', work_order %></td>
                <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
                <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td style="display: none"></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>
  

<br>
    <%= link_to 'New Work Order', new_work_order_path, class: "btn btn-primary white", style: "float: right;" %>

  </div>
</div>

<hr>

<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Work Order Requests
  </div>
  <div class="card-body">
  <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Location</th>
              <th>Issue</th>
              <th>Line</th>
              <th>Machine</th>
              <th>Type</th>
              <th>Request date time</th>
              <th>Level of issue</th>
              <th>Requested by</th>
              <th>Email</th>
              <th>Description of issue</th>
              <th>Planned date and time</th>
              <th>Complete date and time</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @work_order_requests.each do |work_order_request| %>
              <tr>
                <td><%= work_order_request.location %></td>
                <td><%= work_order_request.issue %></td>
                <td><%= work_order_request.line %></td>
                <td><%= work_order_request.machine %></td>
                <td><%= work_order_request.work_order_type %></td>
                <td><%= work_order_request.request_date_time %></td>
                <td><%= work_order_request.level_of_issue %></td>
                <td><%= work_order_request.requested_by %></td>
                <td><%= work_order_request.email %></td>
                <td><%= work_order_request.description_of_issue %></td>
                <td><%= work_order_request.planned_date_and_time %></td>
                <td><%= work_order_request.complete_date_and_time %></td>
                <td><%= link_to 'Confirm', work_order_request_confirm_path(work_order_request), method: :post %></td>
                <td><%= link_to 'Deny', work_order_request_deny_path(work_order_request), method: :post %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

</div>

app/views/work_orders/new.html.erb
<h1>New Work Order</h1>

<%= render 'form', work_order: @work_order %>

<%= link_to 'Back', work_orders_path %>

app/views/work_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @work_order.location %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @work_order.issue %>
</p>

<p>
  <strong>Line:</strong>
  <%= @work_order.line %>
</p>

<p>
  <strong>Machine:</strong>
  <%= @work_order.machine %>
</p>

<p>
  <strong>Type:</strong>
  <%= @work_order.work_order_type %>
</p>

<p>
  <strong>Request date time:</strong>
  <%= @work_order.request_date_time %>
</p>

<p>
  <strong>Level of issue:</strong>
  <%= @work_order.level_of_issue %>
</p>

<p>
  <strong>Requested by:</strong>
  <%= @work_order.requested_by %>
</p>

<p>
  <strong>Email:</strong>
  <%= @work_order.email %>
</p>

<p>
  <strong>Description of issue:</strong>
  <%= @work_order.description_of_issue %>
</p>

<p>
  <strong>Planned date and time:</strong>
  <%= @work_order.planned_date_and_time %>
</p>

<p>
  <strong>Complete date and time:</strong>
  <%= @work_order.complete_date_and_time %>
</p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>